[alembic]
script_location = src/migrations
prepend_sys_path = src
path_separator = os

# Connection URL is set in env.py from configs.settings.
sqlalchemy.url = driver://user:pass@localhost/dbname


[post_write_hooks]
hooks = ruff_format, ruff_check, ruff_format_post

ruff_format.type = exec
ruff_format.executable = uv
ruff_format.options = run ruff format REVISION_SCRIPT_FILENAME

ruff_check.type = exec
ruff_check.executable = uv
ruff_check.options = run ruff check --fix REVISION_SCRIPT_FILENAME

ruff_format_post.type = exec
ruff_format_post.executable = uv
ruff_format_post.options = run ruff format REVISION_SCRIPT_FILENAME
